USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS DENIAL_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60;
CREATE DATABASE IF NOT EXISTS DENIAL_ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS DENIAL_ANALYTICS_DB.RAW;
CREATE STAGE IF NOT EXISTS DENIAL_ANALYTICS_DB.RAW.CLAIMS_STAGE;

LIST @DENIAL_ANALYTICS_DB.RAW.CLAIMS_STAGE;